//! Moving the templates a board is configured from between instances: out as one YAML file, and back in.
//!
//! **A plain file rather than an archive**, unlike a project export. Templates are configuration — a
//! handful of ids, names and colours — so there is nothing to stream and nothing to put in a folder, and a
//! single readable document is the artefact somebody actually wants: it can be reviewed in a diff, edited
//! by hand, and kept in a repository next to whatever else describes how a team works.
//!
//! Prose still travels base64 and everything else stays legible, exactly as in the project format — see
//! [`super::transfer_encoding`] for why the two share that decision rather than each making it.
//!
//! **This is what closes the gap the project import reports.** A project carries the *id* of the templates
//! it follows, not the templates themselves, so pouring a board onto a fresh instance leaves it pointing at
//! configuration that is not there. Bringing the templates over first is the other half of that move, and
//! it is deliberately a separate act: templates are shared by every project on the instance, so importing
//! them is not something that should happen as a side effect of importing one board.

use std::collections::BTreeSet;

use ahash::AHashSet;
use rust_extensions::AsStr;
use rust_extensions::date_time::DateTimeAsMicroseconds;
use serde::{Deserialize, Serialize};
use service_sdk::my_telemetry::MyTelemetryContext;
use task_manager_shared::projects::is_anchor_column;

use crate::app::AppContext;
use crate::board::{ColumnModel, ColumnTemplateModel, KindModel, KindTemplateModel};
use crate::postgres::{ColumnTemplateDto, KindTemplateDto};

use super::transfer_encoding::{decode_moment, decode_text, encode_moment, encode_text, file_name_date};
use super::SkippedImport;

/// What the file says it is.
///
/// Its own version, separate from the project format's: the two are different documents with different
/// lifetimes, and tying them together would mean a change to one forcing a version bump on the other.
pub const FORMAT: &str = "task-manager-templates/1";

/// The most one import may carry.
///
/// Not a technical ceiling — templates are configuration, and an instance with more than this many is not a
/// configured instance, it is a file somebody generated by accident.
pub const MAX_IMPORT_TEMPLATES: usize = 200;

/// The whole file.
#[derive(Serialize, Deserialize, Debug, Default)]
pub struct TemplatesFile {
    #[serde(default)]
    pub format: String,
    #[serde(default)]
    pub exported: String,
    // Both lists are optional, so a file carrying only one kind is legitimate — somebody moving just their
    // columns should not have to write an empty `kind_templates: []` to be understood.
    #[serde(default)]
    pub column_templates: Vec<ColumnTemplateFileModel>,
    #[serde(default)]
    pub kind_templates: Vec<KindTemplateFileModel>,
}

/// One named set of columns.
///
/// `id` is carried and is the identity — unlike a task's number, which is re-issued. A template id is typed
/// in by a person, is never renamed, and is what a project's `column_template_id` points at; re-minting it
/// on import would mean a project export naming `default` could never find the template it came with.
#[derive(Serialize, Deserialize, Debug)]
pub struct ColumnTemplateFileModel {
    pub id: String,
    pub name_base64: String,
    #[serde(default)]
    pub description_base64: String,
    #[serde(default)]
    pub columns: Vec<ColumnFileModel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
}

/// One column. Todo and Done are not here — they exist in every project by definition.
#[derive(Serialize, Deserialize, Debug)]
pub struct ColumnFileModel {
    pub id: String,
    pub name_base64: String,
    #[serde(default)]
    pub description_base64: String,
    pub order: i32,
}

/// One named set of task types. Same identity rules as the columns above.
#[derive(Serialize, Deserialize, Debug)]
pub struct KindTemplateFileModel {
    pub id: String,
    pub name_base64: String,
    #[serde(default)]
    pub description_base64: String,
    #[serde(default)]
    pub kinds: Vec<KindFileModel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
}

/// One task type. `color` is a palette name and `icon` a file name in the UI bundle — both open
/// vocabularies, both left as text, so a value this build does not know reads as the default rather than
/// failing the import.
#[derive(Serialize, Deserialize, Debug)]
pub struct KindFileModel {
    pub id: String,
    pub name_base64: String,
    #[serde(default)]
    pub description_base64: String,
    pub color: String,
    #[serde(default)]
    pub icon: String,
}

/// A finished export: the bytes and what the browser saves them as.
pub struct ExportedTemplates {
    pub file_name: String,
    pub content: Vec<u8>,
}

/// Every template on this instance, as one YAML document.
///
/// Served from memory — templates live on the board — so this is a serialise and nothing else. Ordered by
/// id on both lists so two exports of an unchanged instance are byte-identical and a diff between two of
/// them shows only what actually changed.
pub fn export_templates(app: &AppContext) -> ExportedTemplates {
    let board = app.board.read();

    let mut column_templates: Vec<ColumnTemplateFileModel> = board
        .get_column_templates()
        .iter()
        .map(|template| ColumnTemplateFileModel {
            id: template.id.clone(),
            name_base64: encode_text(&template.name),
            description_base64: encode_text(&template.description),
            columns: template
                .columns
                .iter()
                .map(|column| ColumnFileModel {
                    id: column.id.clone(),
                    name_base64: encode_text(&column.name),
                    description_base64: encode_text(&column.description),
                    order: column.order,
                })
                .collect(),
            created: Some(encode_moment(template.created)),
        })
        .collect();

    column_templates.sort_by(|left, right| left.id.cmp(&right.id));

    let mut kind_templates: Vec<KindTemplateFileModel> = board
        .get_kind_templates()
        .iter()
        .map(|template| KindTemplateFileModel {
            id: template.id.clone(),
            name_base64: encode_text(&template.name),
            description_base64: encode_text(&template.description),
            kinds: template
                .kinds
                .iter()
                .map(|kind| KindFileModel {
                    id: kind.id.clone(),
                    name_base64: encode_text(&kind.name),
                    description_base64: encode_text(&kind.description),
                    color: kind.color.as_str().to_string(),
                    icon: kind.icon.clone(),
                })
                .collect(),
            created: Some(encode_moment(template.created)),
        })
        .collect();

    kind_templates.sort_by(|left, right| left.id.cmp(&right.id));

    drop(board);

    let now = DateTimeAsMicroseconds::now();

    let file = TemplatesFile {
        format: FORMAT.to_string(),
        exported: encode_moment(now),
        column_templates,
        kind_templates,
    };

    // `expect` rather than a Result: every field is a String, a Vec or an i32, and serde_yaml cannot fail
    // on those. A Result here would be an error nobody could ever produce and every caller would have to
    // pretend to handle.
    let yaml = serde_yaml::to_string(&file).expect("templates serialise to yaml");

    ExportedTemplates {
        file_name: format!("templates-{}.yaml", file_name_date(now)),
        content: yaml.into_bytes(),
    }
}

/// What an import did.
pub struct TemplatesImportOutcome {
    pub column_templates_created: usize,
    pub column_templates_replaced: usize,
    pub kind_templates_created: usize,
    pub kind_templates_replaced: usize,
    pub skipped: Vec<SkippedImport>,
    pub notes: Vec<String>,
}

/// Read a templates file and apply it.
///
/// **Keyed by id, and a template already here is REPLACED.** That is the whole point of the feature — the
/// file is the configuration somebody wants this instance to have — but it is also the sharp edge, because
/// a template is followed by projects and replacing one changes every board that follows it in the same
/// write. A column dropped by the replacement does not delete anything: tasks parked in it keep their
/// stored status and read as Todo, and putting the column back brings them home. The count of affected
/// projects is reported so the blast radius is visible rather than discovered.
///
/// **Partial by design**, like every import here: a template that fails validation is reported with the
/// reason and the rest still arrives. Validation is the same code the Settings screen goes through —
/// `validate_column_id`, `validate_task_type_id`, `parse_kind_color`, `is_anchor_column` — so a file cannot
/// put something on this instance that the UI would refuse to save.
pub async fn import_templates(
    app: &AppContext,
    content: &[u8],
) -> Result<TemplatesImportOutcome, String> {
    let text = std::str::from_utf8(content)
        .map_err(|_| "that file is not UTF-8 text — a templates export is YAML".to_string())?;

    if text.trim().is_empty() {
        return Err("that file is empty".to_string());
    }

    let file: TemplatesFile = serde_yaml::from_str(text)
        .map_err(|err| format!("that file could not be read as a templates export: {err}"))?;

    if file.format != FORMAT {
        return Err(if file.format.trim().is_empty() {
            format!("that file does not say what it is — a templates export starts with `format: {FORMAT}`")
        } else {
            format!(
                "this file says it is '{}', and this build reads '{FORMAT}'",
                file.format
            )
        });
    }

    let total = file.column_templates.len() + file.kind_templates.len();

    if total > MAX_IMPORT_TEMPLATES {
        return Err(format!(
            "this file holds {total} templates, and the limit for one import is {MAX_IMPORT_TEMPLATES}"
        ));
    }

    if total == 0 {
        return Err("that file holds no templates".to_string());
    }

    let mut outcome = TemplatesImportOutcome {
        column_templates_created: 0,
        column_templates_replaced: 0,
        kind_templates_created: 0,
        kind_templates_replaced: 0,
        skipped: Vec::new(),
        notes: Vec::new(),
    };

    // Ids seen in THIS file, so one listing the same template twice is refused per duplicate rather than
    // silently applying the last one — the same rule the project import holds its cards to.
    let mut seen: BTreeSet<String> = BTreeSet::new();

    // Every project that follows something this import touched. Collected rather than notified as we go, so
    // a project following both a replaced column template and a replaced kind template is pushed once.
    let mut affected: AHashSet<String> = AHashSet::new();

    let telemetry = MyTelemetryContext::create_empty();

    for src in &file.column_templates {
        match build_column_template(app, src, &mut seen) {
            Ok((template, replaced)) => {
                let followers = followers_of_column_template(app, &template.id);

                let dto: ColumnTemplateDto = (&template).into();
                app.column_templates_repo.upsert(&dto, &telemetry).await;
                app.board.upsert_column_template(template);

                affected.extend(followers.iter().cloned());

                if replaced {
                    outcome.column_templates_replaced += 1;

                    if !followers.is_empty() {
                        outcome.notes.push(format!(
                            "column template '{}' is followed by {} project(s), whose boards just changed shape",
                            src.id.trim().to_lowercase(),
                            followers.len()
                        ));
                    }
                } else {
                    outcome.column_templates_created += 1;
                }
            }
            Err(err) => outcome.skipped.push(SkippedImport {
                name: src.id.clone(),
                reason: err,
            }),
        }
    }

    for src in &file.kind_templates {
        match build_kind_template(app, src, &mut seen) {
            Ok((template, replaced)) => {
                let followers = followers_of_kind_template(app, &template.id);

                let dto: KindTemplateDto = (&template).into();
                app.kind_templates_repo.upsert(&dto, &telemetry).await;
                app.board.upsert_kind_template(template);

                affected.extend(followers.iter().cloned());

                if replaced {
                    outcome.kind_templates_replaced += 1;

                    if !followers.is_empty() {
                        outcome.notes.push(format!(
                            "task-type template '{}' is followed by {} project(s), whose stickers just changed",
                            src.id.trim().to_lowercase(),
                            followers.len()
                        ));
                    }
                } else {
                    outcome.kind_templates_created += 1;
                }
            }
            Err(err) => outcome.skipped.push(SkippedImport {
                name: src.id.clone(),
                reason: err,
            }),
        }
    }

    // After every write, so a project is redrawn from the state the whole import left behind rather than
    // from a half-applied one.
    for project_id in affected {
        app.notify_project_changed(&project_id).await;
    }

    Ok(outcome)
}

/// One column template out of the file, and whether it replaces one that is already here.
fn build_column_template(
    app: &AppContext,
    src: &ColumnTemplateFileModel,
    seen: &mut BTreeSet<String>,
) -> Result<(ColumnTemplateModel, bool), String> {
    let id = template_id(&src.id, seen)?;

    let name = decode_text(&src.name_base64, "a template name")?;

    if name.trim().is_empty() {
        return Err("a column template needs a name".to_string());
    }

    let mut columns: Vec<ColumnModel> = Vec::with_capacity(src.columns.len());

    for column in &src.columns {
        let column_id = super::validate_column_id(&column.id)?;

        // Todo and Done exist in every project and are added by every reader. A template carrying one would
        // draw it twice, and a task could then sit in a "todo" that is not the anchor. Same refusal the
        // Settings screen makes.
        if is_anchor_column(&column_id) {
            return Err(format!(
                "'{column_id}' is one of the two columns every project already has — it cannot be in a template"
            ));
        }

        if columns.iter().any(|itm| itm.id == column_id) {
            return Err(format!("column '{column_id}' is listed twice"));
        }

        let column_name = decode_text(&column.name_base64, "a column name")?;

        if column_name.trim().is_empty() {
            return Err(format!("column '{column_id}' needs a name"));
        }

        columns.push(ColumnModel {
            id: column_id,
            name: column_name.trim().to_string(),
            description: decode_text(&column.description_base64, "a column description")?
                .trim()
                .to_string(),
            order: column.order,
        });
    }

    // Sorted on the way in, so every reader downstream is already in board order — exactly as the save path
    // leaves it.
    columns.sort_by_key(|itm| itm.order);

    // Replacing keeps the moment the template was first created HERE, not the one in the file: on this
    // instance it has existed since it existed here, and taking the file's date would rewrite that history.
    // A template that is new here takes the file's date, which is the honest answer for one that is
    // arriving from somewhere it has lived for a year.
    let existing = app.board.read().get_column_template(&id);
    let replaced = existing.is_some();

    let created = match &existing {
        Some(existing) => existing.created,
        None => match src.created.as_deref() {
            Some(created) => decode_moment(created, "a template's created")?,
            None => DateTimeAsMicroseconds::now(),
        },
    };

    Ok((
        ColumnTemplateModel {
            id,
            name: name.trim().to_string(),
            description: decode_text(&src.description_base64, "a template description")?
                .trim()
                .to_string(),
            columns,
            created,
        },
        replaced,
    ))
}

/// One task-type template out of the file, and whether it replaces one that is already here.
fn build_kind_template(
    app: &AppContext,
    src: &KindTemplateFileModel,
    seen: &mut BTreeSet<String>,
) -> Result<(KindTemplateModel, bool), String> {
    let id = template_id(&src.id, seen)?;

    let name = decode_text(&src.name_base64, "a template name")?;

    if name.trim().is_empty() {
        return Err("a task-type template needs a name".to_string());
    }

    let mut kinds: Vec<KindModel> = Vec::with_capacity(src.kinds.len());

    for kind in &src.kinds {
        let kind_id = super::validate_task_type_id(&kind.id)?;

        if kinds.iter().any(|itm| itm.id == kind_id) {
            return Err(format!("task type '{kind_id}' is listed twice"));
        }

        let kind_name = decode_text(&kind.name_base64, "a task type name")?;

        if kind_name.trim().is_empty() {
            return Err(format!("task type '{kind_id}' needs a name"));
        }

        kinds.push(KindModel {
            id: kind_id,
            name: kind_name.trim().to_string(),
            description: decode_text(&kind.description_base64, "a task type description")?
                .trim()
                .to_string(),
            // Refused rather than defaulted, unlike a colour READ off a stored row: a stored one is data
            // this build may not know yet, where a colour in a file is a claim being made now, and
            // accepting a misspelling silently would repaint somebody's board grey without saying so.
            color: super::parse_kind_color(&kind.color)?,
            // Not validated against anything, exactly as the save path leaves it: the icons are files in
            // the UI bundle and the server has no business knowing which ones shipped. An unknown name
            // draws as no icon.
            icon: kind.icon.trim().to_string(),
        });
    }

    let existing = app.board.read().get_kind_template(&id);
    let replaced = existing.is_some();

    let created = match &existing {
        Some(existing) => existing.created,
        None => match src.created.as_deref() {
            Some(created) => decode_moment(created, "a template's created")?,
            None => DateTimeAsMicroseconds::now(),
        },
    };

    Ok((
        KindTemplateModel {
            id,
            name: name.trim().to_string(),
            description: decode_text(&src.description_base64, "a template description")?
                .trim()
                .to_string(),
            kinds,
            created,
        },
        replaced,
    ))
}

/// A template id from the file, normalised and checked for being said twice.
///
/// Held to the same rule a column id is, because it is the same kind of thing: hand-typed, lower-cased and
/// immutable once created. An id that is empty is refused rather than generated — a generated one would
/// make the import create a second copy of a template on every run.
fn template_id(src: &str, seen: &mut BTreeSet<String>) -> Result<String, String> {
    let id = src.trim().to_lowercase();

    if id.is_empty() {
        return Err("a template in this file has no id — an id is what says which template it is".to_string());
    }

    if id.len() > 64 {
        return Err(format!("'{id}' is too long for a template id"));
    }

    if !id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(format!(
            "'{id}' is not a usable template id: use ASCII letters, digits, '-' or '_'"
        ));
    }

    if !seen.insert(id.clone()) {
        return Err(format!("'{id}' is in this file more than once — an id names one template"));
    }

    Ok(id)
}

fn followers_of_column_template(app: &AppContext, template_id: &str) -> Vec<String> {
    app.board
        .read()
        .projects()
        .iter()
        .filter(|itm| itm.column_template_id.as_deref() == Some(template_id))
        .map(|itm| itm.id.clone())
        .collect()
}

fn followers_of_kind_template(app: &AppContext, template_id: &str) -> Vec<String> {
    app.board
        .read()
        .projects()
        .iter()
        .filter(|itm| itm.kind_template_id.as_deref() == Some(template_id))
        .map(|itm| itm.id.clone())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An id is the identity of a template and is never re-minted, so the rules on it are the strict ones —
    /// and a file saying the same id twice is a file that would otherwise apply only its last copy.
    #[test]
    fn a_template_id_is_normalised_and_may_be_said_only_once() {
        let mut seen = BTreeSet::new();

        assert_eq!(template_id("  Default ", &mut seen).unwrap(), "default");
        assert_eq!(template_id("with-dash_1", &mut seen).unwrap(), "with-dash_1");

        // Said twice, in either spelling.
        assert!(template_id("DEFAULT", &mut seen).is_err());

        assert!(template_id("", &mut seen).is_err());
        assert!(template_id("   ", &mut seen).is_err());
        assert!(template_id("has space", &mut seen).is_err());
        assert!(template_id("кириллица", &mut seen).is_err());
    }

    /// The file has to say what it is. Both failures are worth their own message: a file that is not an
    /// export at all, and one from a version this build cannot apply.
    #[test]
    fn the_format_marker_is_what_makes_a_file_readable() {
        let empty: TemplatesFile = serde_yaml::from_str("column_templates: []").unwrap();
        assert_eq!(empty.format, "");
        assert!(empty.column_templates.is_empty());
        assert!(empty.kind_templates.is_empty());

        // A file carrying only one of the two lists is legitimate.
        let one_kind: TemplatesFile = serde_yaml::from_str(&format!(
            "format: {FORMAT}\nexported: 2026-08-06T09:00:00.000000Z\nkind_templates: []\n"
        ))
        .unwrap();

        assert_eq!(one_kind.format, FORMAT);
        assert!(one_kind.column_templates.is_empty());
    }

    /// What the export writes has to be what the import reads — the one test that would catch a field
    /// renamed on one side only.
    #[test]
    fn the_file_round_trips_through_yaml() {
        let file = TemplatesFile {
            format: FORMAT.to_string(),
            exported: "2026-08-06T09:00:00.000000Z".to_string(),
            column_templates: vec![ColumnTemplateFileModel {
                id: "default".to_string(),
                name_base64: encode_text("Default"),
                description_base64: encode_text("The usual board:\n  with a colon"),
                columns: vec![ColumnFileModel {
                    id: "review".to_string(),
                    name_base64: encode_text("In review"),
                    description_base64: encode_text(""),
                    order: 2,
                }],
                created: Some("2026-01-01T00:00:00.000000Z".to_string()),
            }],
            kind_templates: vec![KindTemplateFileModel {
                id: "work".to_string(),
                name_base64: encode_text("Work"),
                description_base64: encode_text(""),
                kinds: vec![KindFileModel {
                    id: "bug".to_string(),
                    name_base64: encode_text("Bug"),
                    description_base64: encode_text(""),
                    color: "red".to_string(),
                    icon: "bug".to_string(),
                }],
                created: None,
            }],
        };

        let yaml = serde_yaml::to_string(&file).unwrap();
        let back: TemplatesFile = serde_yaml::from_str(&yaml).unwrap();

        assert_eq!(back.format, FORMAT);
        assert_eq!(back.column_templates[0].id, "default");
        assert_eq!(back.column_templates[0].columns[0].order, 2);
        assert_eq!(
            decode_text(&back.column_templates[0].description_base64, "x").unwrap(),
            "The usual board:\n  with a colon"
        );
        assert_eq!(back.kind_templates[0].kinds[0].color, "red");
        assert_eq!(back.kind_templates[0].kinds[0].icon, "bug");
        // Absent stays absent rather than becoming an empty string a date parser would choke on.
        assert!(back.kind_templates[0].created.is_none());
    }
}
