//! The task-type icons that shipped in this bundle.
//!
//! `TASK_ICONS` is generated by `build.rs` from `public/assets/images/task-icons`, so adding an icon is
//! dropping an SVG in that directory and rebuilding.

include!(concat!(env!("OUT_DIR"), "/task_icons.rs"));

/// The URL an icon is served from. Relative, so it resolves against the page origin like every other
/// asset.
pub fn icon_url(name: &str) -> String {
    format!("/assets/images/task-icons/{name}.svg")
}

/// Whether this build actually has that icon.
///
/// A name stored before the file was renamed or removed draws as no icon rather than as a broken image —
/// the same leniency an unknown colour or an unknown column id gets.
pub fn icon_exists(name: &str) -> bool {
    !name.is_empty() && TASK_ICONS.contains(&name)
}
