use std::path::Path;

/// Where the task-type icons live. Served as static assets, so the picker and the board reference them by
/// URL — nothing is inlined into the wasm.
const TASK_ICONS_DIR: &str = "./public/assets/images/task-icons";

fn main() {
    // **Without this the stylesheet silently stops rebuilding.** `generate_task_icons_list` below emits a
    // `cargo:rerun-if-changed` of its own, and the moment a build script emits ANY of those, cargo stops
    // watching the crate wholesale and watches ONLY what was named — so an edit under `css/` is picked up
    // on the next build something ELSE happens to trigger, and not before. That failure has the worst
    // shape a build failure has: no error, a green build, and a browser served the previous stylesheet.
    println!("cargo:rerun-if-changed=./css");

    ci_utils::css::CssCompiler::new("./css")
        .add_file("01-tokens.css")
        .add_file("02-shell.css")
        .add_file("03-forms.css")
        .add_file("04-table.css")
        .add_file("05-board.css")
        .add_file("06-auth.css")
        .add_file("07-dialog.css")
        .add_file("08-goals.css")
        .add_file("09-markdown.css")
        .add_file("10-documents.css")
        .add_file("11-releases.css")
        .add_file("12-timeline.css")
        .compile("./public/assets/app.css");

    generate_task_icons_list();
}

/// Emit the list of available icon names, read off the directory at build time.
///
/// Generated rather than hand-written so dropping a new SVG in is the whole job: the picker offers
/// whatever is on disk, and a name in the database that no longer has a file simply draws as no icon. A
/// hand-maintained list would drift from the directory in both directions, and the failure would be a
/// missing icon nobody could explain.
fn generate_task_icons_list() {
    // Re-run when the directory's contents change, which is what makes "drop a file in and rebuild" work.
    println!("cargo:rerun-if-changed={TASK_ICONS_DIR}");

    let mut names: Vec<String> = Vec::new();

    match std::fs::read_dir(TASK_ICONS_DIR) {
        Ok(entries) => {
            for entry in entries.flatten() {
                let path = entry.path();

                if path.extension().and_then(|itm| itm.to_str()) != Some("svg") {
                    continue;
                }

                if let Some(stem) = path.file_stem().and_then(|itm| itm.to_str()) {
                    names.push(stem.to_string());
                }
            }
        }
        // No directory is not a build failure — it means no icons, and the picker offers "none" only.
        Err(err) => println!("cargo:warning=task icons: {TASK_ICONS_DIR} unreadable: {err}"),
    }

    // Sorted so the picker's order is the same on every machine, rather than whatever order the
    // filesystem happened to hand back.
    names.sort();

    let mut generated = String::from(
        "// Generated by build.rs from public/assets/images/task-icons — do not edit.\npub const TASK_ICONS: &[&str] = &[\n",
    );

    for name in &names {
        generated.push_str(&format!("    {name:?},\n"));
    }

    generated.push_str("];\n");

    let out =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is always set for a build script"))
            .join("task_icons.rs");

    std::fs::write(&out, generated).expect("task icons: cannot write the generated list");
}
